# this mostly run time
services:
  http_backend:
    container_name: sketch_http
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    image: sketcha-http   #if image available don't do build
    #this things is in runtime even image too
    # docker run -p 3001:3001 -e DATABASE_URL="your_value"\
    #  -e DIRECT_URL="your_value" http_backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_yM4kxI3dhQCw@ep-icy-mouse-a14aoi8l-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - DIRECT_URL=postgresql://neondb_owner:npg_yM4kxI3dhQCw@ep-icy-mouse-a14aoi8l.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - JWT_SECRET=123123
    restart: always

  ws_backend:
    container_name: sketch_ws
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    image: sketcha-ws
    ports:
      - "8080:8080"
    environment:
      # - DATABASE_URL=${DATABASE_URL}
      # - DIRECT_URL=${DIRECT_URL}
      # - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgresql://neondb_owner:npg_yM4kxI3dhQCw@ep-icy-mouse-a14aoi8l-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - DIRECT_URL=postgresql://neondb_owner:npg_yM4kxI3dhQCw@ep-icy-mouse-a14aoi8l.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - JWT_SECRET=123123
    depends_on:
      - http_backend
    restart: always

  web_frontend:
    container_name: sketch_web
    build:
      context: .
      dockerfile: docker/Dockerfile.web  #build the image
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3001
        NEXT_PUBLIC_API_WS_URL: http://localhost:8080
    image: sketcha-web
    ports:
      - "3000:3000"
    environment:
      - INTERNAL_API_URL=http://http_backend:3001
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - INTERNAL_API_WS_URL=http://ws_backend:8080
      - NEXT_PUBLIC_API_WS_URL=http://localhost:8080
    depends_on:
      - http_backend
      - ws_backend
    restart: always