
services:
  http_backend:
    container_name: sketch_http
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    image: sketcha-http   #if image available don't do build
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    restart: always

  ws_backend:
    container_name: sketch_ws
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    image: sketcha-ws
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - http_backend
    restart: always

  web_frontend:
    container_name: sketch_web
    build:
      context: .
      dockerfile: docker/Dockerfile.web  #build the image
    image: sketcha-web
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - INTERNAL_API_URL=http://http_backend:3001
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080
      - INTERNAL_API_WS_URL=http://ws_backend:8080
    depends_on:
      - http_backend
    restart: always